import smtplib
from email.message import EmailMessage

msg = EmailMessage()
msg["From"] = "failed-noKPM-dev@porsche-engineering.de"
msg["To"] = "mohammad_jaffar.allah_bakash@porsche-engineering.de"
msg["Subject"] = "[Action Needed] Failed test without KPM — MLBEVO-99999 (SAMPLE)"

plain = (
    "Hi Mohammad Jaffar,\n\n"
    "Test MLBEVO-99999 is marked FAIL with no KPM linked.\n"
    "Please create a KPM ticket and add it to the test run comment.\n\n"
    "Test Plan: MLBEVO-17821\n"
    "Jira: https://skyway.porsche.com/jira/browse/MLBEVO-99999\n\n"
    "---\n"
    "This is a sample email from the MLB TestPlan MCP server.\n"
)

html = """<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;font-size:14px;color:#222;max-width:600px;margin:0 auto;">
  <div style="background:#1a1a2e;padding:18px 24px;border-radius:8px 8px 0 0;">
    <h2 style="color:#fff;margin:0;font-size:1.1rem;">&#9888; Action Required: Failed Test Without KPM</h2>
  </div>
  <div style="border:1px solid #ddd;border-top:none;padding:24px;border-radius:0 0 8px 8px;">
    <p>Hi Mohammad Jaffar,</p>
    <p>The following test has been marked as <strong>FAIL</strong> but has <strong>no KPM ticket</strong> linked to it:</p>
    <table style="border-collapse:collapse;width:100%;margin:16px 0;">
      <tr style="background:#f4f4f4;">
        <td style="padding:8px 12px;font-weight:600;width:140px;">Test Key</td>
        <td style="padding:8px 12px;"><a href="https://skyway.porsche.com/jira/browse/MLBEVO-99999" style="color:#0052cc;">MLBEVO-99999</a></td>
      </tr>
      <tr>
        <td style="padding:8px 12px;font-weight:600;">Test Plan</td>
        <td style="padding:8px 12px;"><a href="https://skyway.porsche.com/jira/browse/MLBEVO-17821" style="color:#0052cc;">MLBEVO-17821</a> &mdash; Sample Test Plan</td>
      </tr>
    </table>
    <p><strong>Please create a KPM ticket</strong> for this failure and link it in the test run comment using the format:</p>
    <pre style="background:#f8f8f8;padding:10px 14px;border-left:4px solid #e00;font-size:13px;">KPM: &lt;kpm-id&gt;</pre>
    <p style="color:#555;font-size:12px;margin-top:24px;">
      This is a <strong>sample email</strong> generated by the MLB TestPlan MCP server.<br>
      Do not reply to this email.
    </p>
  </div>
</body>
</html>"""

msg.set_content(plain)
msg.add_alternative(html, subtype="html")

with smtplib.SMTP("appmail.emea.porsche.biz", 25, timeout=30) as smtp:
    smtp.send_message(msg)

print("Email sent successfully!")
